name: Build

on: 
  push:
  pull_request:
  release:
    types: [created, edited, released]

jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y systemd systemd-container debootstrap
      - name: Fix resolv.conf
        run: |
          echo "nameserver 1.0.0.1" | sudo tee /etc/resolv.conf
          echo "nameserver 1.1.1.1" | sudo tee /etc/resolv.conf
          cat /etc/resolv.conf

      - name: Create build dir
        run: mkdir build

      - name: Build basefs
        working-directory: build
        run: sudo ../builder/build.sh

      - name: Upload tar
        uses: actions/upload-artifact@v2.2.0
        with:
          name: base.sqsh
          path: build/base.sqsh
  